---
- name: jenkinsリポジトリをDL
  get_url: url="http://pkg.jenkins-ci.org/redhat/jenkins.repo" dest=/etc/yum.repos.d/jenkins.repo

- name: リポジトリを登録
  command: rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

- name: 依存関係をインストール
  yum: name=java-1.7.0-openjdk state=latest

- name: jenkinsをインストール
  yum: name=jenkins state=latest

- name: 設定ファイルjenkinsを設定
  copy: src=jenkins dest=/etc/sysconfig/jenkins

- name: jenkinsを起動
  service: name=jenkins state=started
